API_v1.md, auth.js, controllers/messages.js, db.js, package.json, server.js, tests/controllers/messages.js
WIP, opening for discussion.  Issue: https://github.com/medic/medic-webapp/issues/817
=> Messages API

API_v1.md, auth.js, controllers/forms.js, controllers/messages.js, controllers/records.js, db-nano.js, package.json, server.js, tests/auth.js, tests/messages.js, tests/records.js
Including a second db module here (db-nano) because this is a backport
from the develop branch.
Issue: medic/medic-webapp/issues/817
Issue: medic/medic-webapp/issues/886
=> initial support for messages, records and forms API.

db.js
=> 1096: strip trailing slash from COUCH_URL if provided

public/login/script.js
=> Select username input field in login form on page load

public/login/script.js, public/login/style.css, templates/login/index.html
=> Allow tab/keyboard focus for submit button on login form

package.json, safe-redirect.js, server.js, tests/safe_redirect.spec.js
=> Fix part2.1

public/login/script.js
=> Fix for firefox username field focus issue

server.js
Issue: medic/medic-webapp#1949
@SCdF you are a terrible person
=> Reference `serverUtils.notLoggedIn()` properly

API_v1.md, controllers/places.js, controllers/users.js, server.js, tests/controllers/places.js, tests/controllers/users.js
Issue: medic/medic-webapp#2046
=> support places better

controllers/users.js, tests/controllers/users.js
=> added support for `external_id` property to users controller.

controllers/messages.js, server.js, tests/messages.js
This arg doesn't seem to do anything.
=> remove district arg from message controller functions

controllers/messages.js, server.js, tests/controllers/messages.js
=> Remove `district` arg from message controller functions

API_v1.md, controllers/people.js, controllers/places.js, controllers/utils.js, tests/controllers/people.js, tests/controllers/places.js
Issue: https://github.com/medic/medic-webapp/issues/2046
=> added support for `reported_date` in people and places APIs.

API_v1.md, controllers/utils.js, tests/controllers/people.js, tests/controllers/places.js, tests/controllers/utils.js
https://github.com/medic/medic-webapp/issues/2046
=> 2046 refactored reported date support

handlers/changes.js, server.js, tests/handlers/changes.js
This is becoming quite complicated but it's still the best solution I can think of, at least in the short term.
=> New docs should replicate. Issue: medic/medic-webapp#2396

migrations/extract-user-settings.js
Issue: medic/medic-webapp#2455
=> Fix typo in extract-user-settings migration

handlers/changes.js, tests/handlers/changes.js
Issue: medic/medic-webapp#2476
=> Clean up changes requests when client aborts. 

controllers/users.js, schedules/usage-stats.js, tests/schedules/usage-stats.js
Main view changes are here: https://github.com/medic/medic-webapp/pull/2599
=> Cleaning up views

migrations/extract-person-contacts.js, tests/migrations/extract-person-contacts.js
=> Do not break extract-person-migration if parent does not exist

migrations/extract-person-contacts.js
Issue: medic/medic-webapp#2595
=> Add documentation to extract-parent-contacts to explain "looping"

server.js
Wow that diffs badly doesn't it. I only wrapped and added the first check
=> Version check medic/medic-webapp#2931 medic/medic-webapp#2854

Gruntfile.js
Issue: medic/medic-webapp#2933
=> Add check for required env vars in Grunt tasks

controllers/sms-gateway.js, tests/unit/controllers/sms-gateway.js
Also, be more tolerant of unknown statuses.
medic/medic-projects#1243
=> Don't change status until receipt acknowledged by gateway

migrations/drop-couchmark-db.js
=> Add migration to remove couchmark db

migrations/create-patient-contacts.js, tests/integration/migrations/create-patient-contacts.js
Migration to create patient person documents from registrations if they don't already exist.
Fixes medic/medic-webapp#3115, medic/medic-webapp#3075 and partially fixes medic/medic-webapp#3082.
=> Patient centric view support

migrations/emit-complete.js, tests/integration/migrations/add-uuid-to-scheduled-tasks.js, tests/integration/migrations/emit-complete.js, tests/integration/migrations/extract-translations.js, tests/integration/migrations/utils.js
=> Migration to add emit _complete to config

public/login/script.js
=> Trim usernames in login controller. medic/medic-webapp#2653

.jshintrc, README.md, server.js
Checks to make sure you've set the right env vars, and that you're on the right version of Node.
=> 3226 env var check

migrations/add-national_admin-role.js
Issue: medic/medic-webapp#3262
=> The national_admin role is now sufficient to edit users

server.js
Issue: medic/medic-webapp#3152
=> Redirect `/api/sms/` requests to `/api/sms`

migrations/add-national_admin-role.js
=> Adds default _security structure if required

is-client-human.js, tests/unit/is-client-human.js
Issue: medic/medic-webapp#3334
Blocked by https://github.com/medic/medic-api/pull/134
=> 3334 set useragent for collect

migrations/namespace-form-fields.js, tests/unit/migrations/namespace-form-fields.js
=> Batch query for namespace-form-fields migration. medic/medic-webapp#3371

migrations/namespace-form-fields.js, tests/unit/migrations/namespace-form-fields.js
=> batch namespace form fields medic/medic-webapp#3371

migrations/namespace-form-fields.js, tests/unit/migrations/namespace-form-fields.js
=> 3371 unbreak api

README.md, controllers/message-utils.js, controllers/sms-gateway.js, package.json, server.js, tests/e2e/controllers/messages.js, tests/e2e/handlers/changes.js, tests/e2e/test-framework.js, tests/e2e/utils.js, tests/unit/controllers/message-utils.js, tests/unit/controllers/sms-gateway.js
=> 3073 message delivery statuses

controllers/forms.js, server.js
Fix for medic/medic-webapp#3390
=> Allow collect to fetch XML forms

migrations/create-patient-contacts.js
The view definition in medic-webapp has changed to not use an array
for a single parameter so this is just updating the calling code to
match.
medic/medic-webapp#2635
=> Updates view parameter formatting

migrations/create-patient-contacts.js
=> Add additional patient name paths to try

handlers/changes.js, tests/unit/handlers/changes.js
To be merged (please don't squash) into the 2.11.x branch, so we can make a 2.11.2 release.
=> 3508 speed up replication (2.11.x)

handlers/changes.js, tests/unit/handlers/changes.js
To be merged (please don't squash) into master. There is a separate PR for 2.11.x: https://github.com/medic/medic-api/pull/158
=> 3508 speed up replication (master)

controllers/people.js, controllers/places.js, tests/unit/controllers/export-data.js, tests/unit/controllers/people.js, tests/unit/controllers/places.js, tests/unit/controllers/users.js, tests/unit/handlers/changes.js
The people and places APIs were missed from the Linked Contacts refactor so were still creating inlined parents and contacts.
medic/medic-webapp#2635
=> Updates people and places APIs to minify contacts

migrations/associate-records-with-people.js, tests/unit/migrations/associate-records-with-people.js
Use bulk updates and a smaller view for performance. Output progress
so user has some idea of how it's going.
medic/medic-webapp#3554
=> Improves performance and reporting of migration

controllers/forms.js, server.js
- 404 when form not found
- 400 when request incomplete
medic/medic-webapp#3569
=> Use correct error codes on forms api

controllers/users.js, package-lock.json, package.json, tests/unit/controllers/users.js
Any passwords passed to createUser or updateUser will now be
validated to be at least 8 characters long and sufficiently
complex.
medic/medic-webapp#1472
=> Adds password strength validation to users api

controllers/forms.js, package-lock.json, package.json
Replacing github links with org packages
medic/medic-webapp#3628
=> Moving to org packages

tests/unit/controllers/forms.js
Hopefully this makes the intent clearer.
Recommend reviewing at https://github.com/medic/medic-api/pull/177/files?w=1
=> Tidy up forms controller unit tests

controllers/login.js, server.js, tests/unit/controllers/login.js
Uses secure, httpOnly, and sameSite flags where possible to
protect users from cookie hacking.
medic/medic-webapp#3182
=> Secures cookies

controllers/forms.js
=> Filter collect forms when generating forms list

handlers/changes.js, package.json
Backport: medic/medic-webapp#3111
Once this is merged I will update the submodule in the medic-webapp https://github.com/medic/medic-webapp/pull/3763.
=> Don't write to finished response

migrations/create-patient-contacts.js
Use a new combined view to get contacts by shortcode or refid.
medic/medic-webapp#3511
=> Update to use contacts_by_reference view

controllers/users.js, lib/user-db.js, tests/unit/controllers/users.js, tests/unit/lib/user-db.js
The invalid characters are converted to their UTF code to reduce
the likelihood of collisions with other databases.
The create user api has been updated to fail validation if the
username has unusual characters.
medic/medic-webapp#3778
=> Escape invalid characters when creating meta db

README.md, auth.js, controllers/upgrade.js, package-lock.json, package.json, server-utils.js, server.js
API now knows how to stage a ddoc from our builds repo for Horticulturalist to then pick up and deploy.
medic/medic-webapp#3749
=> Horticulturalist upgrade support

config.default.json
Allow partners to see clinic in the place hierarchy if they wish.
medic/medic-webapp#3902
=> Make place hierarchy configurable

README.md
=> Add legacy note
