medic/medic-api

public/login/style.css

Text in the input fields is really small on:
* medic-android
* chrome
* firefox
This PR should make text the same size as for the text labels.

Make the font bigger in the login screen input boxes

---

controllers/forms.js
db-nano.js
tests/forms.js

Added a `db.sanitizeResponse` that can be called from any controller.  The only
problematic function right now is `forms.getForm` because it returned headers
coming from nano.  Sanitized those headers by removing `uri` and `statusCode`
and wrote tests around it.  This could potentially leak auth information to the
client.  See https://github.com/dscape/nano/blob/master/lib/nano.js#L195
TODO: open issue in nano project and patch
Issue medic/medic-webapp#1844

sanitize requests in the forms controller. 

---

ddoc-extraction.js
server.js
tests/ddoc-extraction.js

This feature supports our ability to have muiltiple DDocs being served out of
the same Kanso project.
On the `medic-webapp` side, all extra Ddocs should be JSON files (with their
correct `_id` etc) inside the `ddocs/compiled` directory. This is then picked
up by Kanso as an attachment and pushed to Couch.
When `medic-api` runs it will run this code. This code looks through all
attached Ddocs, and re-uploads them if it thinks it should.

Automatic DDoc extraction #36

---

migrations/convert-bad-dob-format.js

Converts and saves bad data like "Apr 13th, 2010" to "2010-04-13",
For issue: medic/medic-webapp#1672

Convert bad date dob format

---

server-utils.js

1. doesn't make much sense to use `console.error` for the initial message and `console.log` for the details, as they may end up in different places.
2. having two separate calls may mean they're separated in the log file (perhaps not, with node?)
3. passing an `Error` to `console.(log|error)()` should end up giving us the stacktrace anyway

Simplify console.log call in server-utils

---

API_v1.md
controllers/utils.js
tests/controllers/people.js
tests/controllers/places.js
tests/controllers/utils.js

This is also the stored format (ms since epoch) so we need to support it
in the validation anyway otherwise validating existing records will
fail.
Also added a bit of centralized documentation about timestamps.  The
other record types (Records) need to be updated still to support the new
format and that will get done soon.
https://github.com/medic/medic-webapp/issues/2449

allow `reported_date` on places/people to use MS since Unix Epoch.

---

migrations/extract-person-contacts.js

**HELLO REVIEWER,** I put this in a PR because I'm not sure on our stance on changing migrations once they're live. This seems like a strict upgrade, but I thought I'd check anyway.
This happened because the errors created attempt to reference the
object that failed to be loaded and caused the error to be created
in the first place.
(it's really hard to explain that concisely)

Errors no longer error medic/medic-webapp#2520

---

controllers/export-data.js
server.js
tests/controllers/export-data.js

Issue #2694
Exports now stream from API instead of being generated as one giant string, reducing memory requirements.
This is a POC that only converts `outputToXml`. It only streams XML generation, not pulling data from CouchDB. This would be the next natural step if we still get memory issues.
I'll work on converting the other output formats to stream as well.

Streaming Exports

---

server.js

- No trailing slash detection has been improved to include standard
db path
- All of the CouchDB API that uses POST but doesn't write (up to 2.0)
is no longer audited

Refining auditing hooks medic/medic-webapp#2895

---

controllers/sms-gateway.js

The `sms-gateway` controller picks up all `pending` messages, and forwards these
to `medic-gateway`.  The controller then changes the messages' status to
`forwarded-to-gateway`.
Issue: #3047

Add new message status for messages forwarded to gateway

---

handlers/changes.js

Don't write to finished response

---

audit-proxy.js
tests/unit/audit-proxy.js

Joining the array of buffers serializes them individually so unicode
characters that cross the packet boundary are corrupted. Using the
Buffer.concat function combines them so the two halves of the
character are reunited before serialization.
medic/medic-webapp#3305

Correctly concatenate request body

---

client_is_human.js
server.js
tests/unit/client_is_human.js

This means that android apps like medic-collect and medic-gateway will receive
status code 401 instead of 302 when they fail to authenticate.
Issue: #3118
...because we all like parsing useragents.

Only redirect to login page if requesting client is human

---

migrations.js
tests/unit/migrations.js

Make it easier to find the migration log as it turns out it's useful
information for humans as well as machines.
medic/medic-webapp#3294

Migrate migration log to have predictable id

---

config.default.json

The duplicate was loading into config fine, and potentially even working
fine, but was causing the permissions menu to fail to render, because
Angular did not like a repeater with the same name.
medic/medic-webapp#3251

Remove duplicate permission

---

server-utils.js
server.js

Issue: medic/medic-webapp#3118
Other commits made in attempting to resolve this issue:
* fec0e015b0484b7be4b58607d1b4e88c7e00c58c
* 819c24eed00b017c6639a4d16a898c6b7bb5d205
It's not currently clear to me why the `WWW-Authenticate` header is set in so many places.

Send basic auth header to Collect

---

migrations/add-uuid-to-scheduled-tasks.js
package.json

Small review, just noticed when doing an `npm install` that node-uuid is the deprecated name.

node-uuid is now just uuid

---

server.js

To prevent accidents, make sure that when api boots CouchDB is not
running the hilariously insecure default "admin party" mode, where no
authentication is required.

Require that CouchDB requires auth

---

migrations/namespace-form-fields.js
tests/integration/migrations/namespace-form-fields.js

The data_records migration emits each doc multiple times so it's
possible to try and update the same document twice in one batch.
Instead we should use a different view that only emits once.
medic/medic-webapp#3534

Modifies migration so it doesn't conflict on update

---

controllers/create-user-db.js
db.js
lib/user-db.js
migrations.js
migrations/extract-read-status.js
server.js
tests/unit/controllers/create-user-db.js
tests/unit/lib/user-db.js
tests/unit/migrations.js

Adds a migration to extract the read status from the docs and
into the meta db.
Adds an endpoint to handle the lazy creation of the user meta
db.
Also improves the migration output to be formatted rather than
stringifying the Error.
medic/medic-webapp#2418

Adds support for storing read status in meta db

---

db.js
lib/db-batch.js
migrations/extract-read-status.js
tests/unit/lib/db-batch.js

Pulls out the db.batch function into lib/db-batch
Uses the startkey strategy instead of skip for improved
performance and removing the chance of missing records due to
view reordering.
medic/medic-webapp#3553

Improves pagination strategy of bulk get

---

controllers/messages.js
tests/unit/controllers/messages.js

If you try to destructure undefined it gives you a really confusing
error message:
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
Instead, if we can't find the task return null, and have our correct
existing error message handle it

Return the correct error message medic/medic-webapp#3587

---

.travis.yml
server.js

Hopefully a clearer explanation
Outputting the incorrect statusCode for debugging in case checking for
401 is not the perfect test
Correctly linking to the (new) README section on security
medic/medic-webapp#3606

Improving security error message medic/medic-webapp#3606

---

controllers/export-data.js
tests/unit/controllers/export-data.js

Exporting reports and messages was broken by the recent linked
contacts change because the exports can return details on the
parents, for example, "parent.name". This hydrates all the db rows
before they get mapped into the output format.
medic/medic-webapp#3593

Hydrates the contacts when exporting

---

controllers/record-utils.js
controllers/sms-gateway.js
tests/unit/controllers/record-utils.js

Allow for empty SMS messages
medic/medic-webapp#3658

Allow for empty sms

---

controllers/messages.js
tests/unit/controllers/messages.js

Instead of erroring simply log the problems and otherwise ignore the bad
data. We want to do this because we don't want to push problems back to
gateway, as gateway is hard to debug or even access, whereas api is in a
nice easy location to view logs and so on.
medic/medic-webapp#3672

Don't throw errors for bad messages medic/medic-webapp#3672

---

handlers/changes.js

When we detect that the patient report references a patient but we
can't find them by the given ID the replication key falls back to
the contact ID. This means that restricted users that can
replicate the CHW can replicate the report.
This allows for the CHW and supervisors to see the report and
resubmit with the correct patient id.
medic/medic-webapp#3437

Replication key falls back to contact

---

tests/unit/translations.js
translations.js

If the messages-xy.properties file has an empty translation value
it will be parsed and stored in our messages-xy doc as null. When
rendering using the angular directive this will safely fall back to
rendering the key, however when translating with the $translate
service an error is thrown. This change sets the value in the
database to the key so the $translate service behaves consistently
with the angular directive.
medic/medic-webapp#3753

Default null translation values to key

---

controllers/record-utils.js
tests/unit/controllers/record-utils.js

The req.body doesn't inherit from Object so doesn't have the
hasOwnProperty function defined.
medic/medic-webapp#3770

Remove assumption of Object inheritance

---

tests/unit/translations.js
translations.js

Uses English as the canonical set of translation keys and ensures
that any languages that are shipped with an incomplete set are
updated to contain all known keys.
medic/medic-webapp#3753

Ensure all languages have all keys

---

server-utils.js
tests/unit/server-utils.js

This improves our error handling so errors being thrown from the
request library do not crash API. From now on any 5xx error is to
be treated as a server error.
medic/medic-webapp#3821

Gracefully handle errors from request lib

---

controllers/record-utils.js
server.js

There were a couple of reasons why the specific error from the original issue was not being made public:
1. that specific example was not being made a `PublicError` instance instead of a standard `Error`
2. calls to `server-utils.serverError()` regularly pass `err.message` as the first argument.  Changing this to `err` is much more useful.  I can't see any obvious problem with changing it, except that logging will start to include stacktraces.  E.g.
```
15:20:20 api.1    | Server error: Missing required value: from
```
would become:
```
15:20:20 api.1    | Server error:
15:20:20 api.1    |  { Error: Missing required value: from
15:20:20 api.1    |     at Object.createByForm (/Users/user/workspaces/medic/api/controllers/record-utils.js:28:21)
15:20:20 api.1    |     at Object.create …
```

Make more errors more public

---

migrations/move-sentinel-metadata.js

This document stores sequence numbers, and so is only relevant on the
specific instance it was created on. Replicating it to another instance
will cause sentinel to behave incorrectly.
medic/medic-webapp#3860

Store sentinel meta-data in a _local document

---

package.json

Specify the 6.4.0 version of nano in the package.json so older
versions of node which don't support the package-lock.json don't
get 6.4.2 which throws a runtime error.
medic/medic-webapp#3963

Lock down the version of nano
